#!/usr/bin/env bash
# creates a new file, appending a counter to the end if the file exists
# based on http://stackoverflow.com/a/12187944/192671
# example: new foo.txt
# TODO: support names with spaces in the extension
# TODO: `new "foo 2.txt"` should create `foo 3.txt`

source $(dirname $0)/lib/filename.sh

if [[ -e $1 ]] ; then
    split_extension "$1"
    i=2
    while [[ -e "$filename $i.$extension" ]] ; do
        let i++
    done
    touch "$filename $i.$extension"
else
    touch $1
fi
